[env:teensy41]
platform = teensy
board = teensy41
framework = arduino

lib_deps = 
    adafruit/Adafruit BusIO
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit BMP3XX Library
    adafruit/Adafruit BNO08x
    adafruit/Adafruit GPS Library

build_flags = 
    -I include
    -I include/sensors

monitor_speed = 9600
upload_protocol = teensy-gui

# 아직 구현 안된 파일들 빌드에서 제외
build_src_filter = 
    +<*>
    -<CMD.cpp>
    -<DCS.cpp>
    -<EggDrop.cpp>
    -<Mode.cpp>
    -<PID.cpp>
    -<Recovery.cpp>
    -<sensors/Servo.cpp>
    -<sensors/Teensy_Camera.cpp>
    -<sensors/XBee_Module.cpp>
    -<sensors/SDCARD.cpp>